* Command help:
** Describe function
C-. f function-name
** What key command is on
C-. w function-name

** What function is bound to a key sequence
C-. c key-sequence (name the function)
C-. k key-sequence (function help)

** Tips
Use C-J for newlines in code

** Describe variable
M-x describe-variable

** Command history variable
command-history

** Describe active modes
M-x describe-mode

** Packages:
M-x list-packages

Update Packages
To update packages, just press 【U x】.

package-menu-mark-upgrades 【U】 → For any package that has a new version, the installed one will be marked “D” (for delete), and new one will be marked “I” (to install).

package-menu-execute 【x】 → run the marked commands on packages.

i - mark for installation
d - mark for deletion
U - Mark all package with a newer available version for “upgrading”
x - Download and install all packages marked with i, and their dependencies; also, delete all packages marked with d (package-menu-execute). This also removes the marks.

** Narrow mode
C-x n n - Narrowing
C-x n w - Widening
